// Generated by CoffeeScript 1.4.0
var Dog, additionalArgs, args, fs, input, inspect, path, uglifyjs,
  __indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

fs = require('fs');

path = require('path');

uglifyjs = (function() {
  try {
    return require('uglify-js');
  } catch (_error) {}
})();

Dog = require('./module');

inspect = function(o) {
  return (require('util')).inspect(o, false, 9e9, true);
};

args = process.argv.slice(1 + (process.argv[0] === 'node'));

additionalArgs = [];

if (__indexOf.call(args, '--') >= 0) {
  additionalArgs = (args.splice(args.indexOf('--'), 9e9)).slice(1);
}

input = args[0];

fs.readFile(options.input, function(err, content) {
  var output;
  if (err != null) {
    throw err;
  }
  output = Dog.compile(content);
  return console.log(output);
});
