// Generated by CoffeeScript 1.4.0
var Parser, fs, path, pkg, uglifyjs;

fs = require('fs');

path = require('path');

uglifyjs = (function() {
  try {
    return require('uglify-js');
  } catch (_error) {}
})();

Parser = require('./parser');

pkg = require(path.join(__dirname, '..', '..', 'package.json'));

module.exports = {
  VERSION: pkg.version,
  Parser: Parser,
  compile: function(markup) {
    try {
      return Parser.parse(dog);
    } catch (e) {
      throw e;
    }
  }
};
